---
# handlers file for setup-apache
    - name: Start httpd
      service:
        name: httpd
        state: started

    - name: Start apache2
      service:
        name: apache2
        state: started

    - name: restart httpd
      service:
        name: httpd
        state: restarted

    - name: restart apache2
      service:
        name: apache2
        state: restarted
