---
- name: installing httpd in this playbook
  hosts: servers
  become: true
  tasks:
  - name: using dnf module
    dnf:
      name: httpd
      state: installed
  - name: using servie  module
    service:
      name: httpd
      state: started
