---
- name: install apache on all servers
  hosts: all
  become: true
  tasks:
    - name: Install httpd on Red Hat based systems
      package:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Start httpd on Red Hat based systems
      service:
        name: httpd
        state: started
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install apache2 on Debian based systems
      package:
        name: apache2-bin
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Start apache2 on Debian based systems
      service:
        name: apache2
        state: started
      when: ansible_facts['os_family'] == "Debian"

